export const EMIT_KEYCODE = 'EMIT_KEYCODE'

export const SELECT_GITHUB_TAB = 'SELECT_GITHUB_TAB'
export const SELECT_PROGRAM_TAB = 'SELECT_PROGRAM_TAB'
export const SET_RUNNING = 'SET_RUNNING'
export const SET_DELAYED = 'SET_DELAYED'
export const START_PROGRAM = 'START_PROGRAM'

export const SET_GITHUB_PROGRAM_TEXT = 'SET_GITHUB_PROGRAM_TEXT'
export const SET_PROGRAM_TEXT = 'SET_PROGRAM_TEXT'
export const CLEAR_PROGRAM = 'CLEAR_PROGRAM'
export const LOAD_PROGRAM = 'LOAD_PROGRAM'
export const SET_IP = 'SET_IP'

export const SET_PROCESSOR_STATE = 'SET_PROCESSOR_STATE'

export const SET_SHIFT_KEY = 'SET_SHIFT_KEY'

export const FETCH_GITHUB_PROGRAM_LIST = 'FETCH_GITHUB_PROGRAM_LIST'
export const FETCH_GITHUB_PROGRAM_TEXT = 'FETCH_GITHUB_PROGRAM_TEXT'
