export default {
  STATE_VERSION: '1.0',
  CONSTANTS_PANEL: 'CONSTANTS_PANEL',
  GITHUB_PANEL: 'GITHUB_PANEL',
  KEYPAD_PANEL: 'KEYPAD_PANEL',
  MEMORY_PANEL: 'MEMORY_PANEL',
  PROGRAM_PANEL: 'PROGRAM_PANEL',
}