export default {
  CONSTANTS_PANEL: 'CONSTANTS_PANEL',
  CONVERSIONS_PANEL: 'CONVERSIONS_PANEL',
  GITHUB_PANEL: 'GITHUB_PANEL',
  KEYPAD_PANEL: 'KEYPAD_PANEL',
  MEMORY_PANEL: 'MEMORY_PANEL',
  PROGRAM_PANEL: 'PROGRAM_PANEL',
}